### PR TITLE
Fixed the invalid file name issue.

### PR DESCRIPTION
**Pull request by itsaboutcode**
Fixed the following build error.
screen shot 2015-05-28 at 12 20 54 pm

### CODE REVIEW

**Comment by itsaboutcode** [comment]
I believe #19 was suppose to fix this issue but it has not. So sending another pull request.

**Comment by adrianonco** [comment]
Oh, really helpful @itsaboutcode, but please, feel free to open the related bounties you consider for award your work ;)
https://assembly.com/giraff/bounties
Thanks so much!!

**Comment by itsaboutcode** [comment]
@adrianonco 
I am new to assembly, so don't know all the protocols. Can I open a bounties now and mention this pull request?

Thanks.

**Comment by adrianonco** [comment]
Sure @itsaboutcode! Thanks for your attitude ;)

**Pull request merged**
