### PR TITLE
Update the drawer layout  #154

### PR DESCRIPTION
**Pull request by alouanemed**
Bounty #154

Upgraded user :
image

Normal user:
image

### CODE REVIEW

**Comment by adrianonco** [comment]
Looks good! Do I merge?

**Comment by seuros** [comment]
There is a typo in the username.... :trollface:

**Comment by adrianonco** [comment]
Haha, yes :) 
@alouanemed, let me know if you need the Gotham Rounded font.

**Comment by intrications** [comment]
@adrianonco 

Have you checked the licence for Gotham Rounded for use in mobile apps? It may not be free.

https://www.quora.com/Is-Gotham-Rounded-a-free-font-and-if-yes-where-can-I-download-it-from
http://www.typography.com/fonts/gotham-rounded/styles/
http://www.typography.com/faq/question.php?faqID=97

**Comment by adrianonco** [comment]
Yep, @intrications, thanks for the notice, but I think Austin is resolving it, isn't it @bshyong?

**Comment by alouanemed** [comment]
@seuros  LOOOL didn't notice that
@adrianonco Once you give me the free font I will add it :)

**Comment by bshyong** [comment]
@alouanemed I think the current font that you're using is fine for our MVP. We can purchase a license for the fonts once we have a unified design and are ready to polish the UI.

**Comment by alouanemed** [comment]
@bshyong Yeah, you are right

**Comment by adrianonco** [comment]
Ups, so sorry, I thought, by a comment to shea, that we could use that font. My apologies. Go with the current one.

**Pull request merged**
