### PR TITLE
Added the facebook SDK and configured it.

### PR DESCRIPTION
**Pull request by darkracer**
This is bounty #99. This fixes the merging issue.

### CODE REVIEW

**Comment by seuros** [comment]
that it ?

**Comment by darkracer** [comment]
No, apparently everything dissapeared.

**Comment by darkracer** [comment]
@seuros This should be it.

**Comment by alouanemed** [comment]
@darkracer  Can you create another activity called DevActivity where you put buttons for each : MainActivity and FacebookActivity, so that we leave the MainActivity contains only the gifs and the drawer .

**Comment by darkracer** [comment]
@alouanemed after running the app a new app should be installed called DevActivity. This contains the facebook button.

**Comment by alouanemed** [comment]
@darkracer  I think you didn't understand me  , you should create a dev activity not fragment ,so it should extends from BaseActivity, and it' going to show normal buttons not facebook's one ,so we will have two buttons:

1-Login facebook
2-MainActivity 

when we click On Loginfacebook button it will launch the activity where the facebook button is located :)

**Comment by alouanemed** [comment]
@darkracer  it's all good .
@seuros ship it :D

**Comment by adrianonco** [comment]
@alouanemed can I merge this then?

**Comment by alouanemed** [comment]
@adrianonco  yeah

**Comment by adrianonco** [comment]
Well dine @darkracer!!

And thanks a lot @alouanemed and @seuros for the revision!

**Pull request merged**
