### PR TITLE
[WIP]  Implement swipeable card view

### PR DESCRIPTION
**Pull request by alouanemed**
I manage to test both lib : 

1- add Swipeable-Cards
2- add image gif view
3- custom adapter
4-custom layout for each gif

### CODE REVIEW

**Comment by darkracer** [comment]
Look's really nice.
There's just one thing.
Sometimes the images are displayed at an angle that is too large. This causes parts of them to fall of the sort of box they are placed in.

There are two fixes:
1. Make sure they have a smaller angle.
2. Make the box as large as the white space.

**Comment by alouanemed** [comment]
@darkracer  :+1:  well  that's not a problem , after we customize the card we will set the max size.
If that's all, I think we should close this !

**Comment by darkracer** [comment]
That sounds like a good idea to me.

**Comment by adrianonco** [comment]
Hey guys, seems a good work but I prefer @bshyong or others merge (I'm not a dev and I could do something wrong). Thanks again!

**Comment by bshyong** [comment]
@alouanemed I'm merging this; thanks. @adrianonco I'm not sure what bounty this one corresponds to but feel free to take care of it

**Comment by alouanemed** [comment]
@bshyong Thanks :)  updated : b#98

**Pull request merged**
